#-------------------------------
# Site Settings
title: SilkQuote - Native Salesforce Quoting That Closes the Loop
description: Easily templatize, generate, and share dynamic quotes that customers can review and accept. Built for Salesforce.
logo: /images/logo.png
install_url: /install
production_install_url: https://login.salesforce.com/packaging/installPackage.apexp?p0=04tVt000001ed6vIAA
sandbox_install_url: https://test.salesforce.com/packaging/installPackage.apexp?p0=04tVt000001ed6vIAA
appexchange_url: 

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Install'
      url: '/install'
    - title: 'Pricing'
      url: '/#pricing'
    - title: 'Support'
      url: '/support/'
    - title: 'Demo'
      url: '#'
      demo: true

#-------------------------------
# Footer Settings

# Footer Navigation
menu__items: 
  - url: '/install/'
    title: 'Install'
  - url: '/support/'
    title: 'Support'    
  - url: '/contact/'
    title: 'Contact'
  - url: '/features/'
    title: 'All Features'    

home__items: 
  - url: '/#differentiators'
    title: 'Differentiators'
  - url: '/#features'
    title: 'Features'
  - url: '/#steps'
    title: 'Steps'
  - url: '/#pricing'
    title: 'Pricing'        
  - url: '/#documentation'
    title: 'Documentation'
  - url: '/#recommended'
    title: 'Templates'                                                        

#-------------------------------
# Hero Settings
hero:
  hero__title: Native Salesforce Quoting That Closes the Loop
  hero__description: Easily templatize, generate, and share dynamic quotes that customers can review and accept in <strong>Salesforce</strong>.
#-------------------------------
# Blog Settings
blog:
  blog__title: Documentation
  blog__description: Learn to use SilkQuote in your quote generation process.

#-------------------------------
# Featured Tag Settings
tag:
  enable: true
  tag__title: Templates
  tag__name: templates

#-------------------------------
# Author Settings
author:
  author__name: Skylar Rhodes
  author__bio: SilkQuote helps sales teams create professional, branded quotes directly within Salesforce. With flexible templates and customizable layouts, teams can generate, preview, and share accurate quotes directly with the customer.<br>It works standalone or alongside existing CPQ tools, giving teams control, reducing manual work, and helping close deals faster!
  author__avatar: /images/avatar.png

#-------------------------------
# Google Analytics
google-analytics: G-PEZ75XV87W
